### PR TITLE
complete celling question from binary search

### PR DESCRIPTION
**Pull request by s4shantanu**
## What type of PR is this? (check all applicable)

- [x] 🚀 Shantanu raut
- [x] ✨ Solve Ceiling question from Binary search 
- [x] 🌟 stared the repo
- [x] 🐛 Grammatical Error
- [x] 📝 Documentation Update
- [x] 🚩 Other

## Description
I solve the ceiling question from binary search programming is running.
Tech - Java

## Add Link of GitHub Profile
https://github.com/s4shantanu

### CODE REVIEW

**Comment by s4shantanu** [comment]
Please check my commit pull request and merge as soon as possible

**Review by s4shantanu — COMMENTED** [review]
The program was running properly please review and approve these changes.

**Comment by kaivalya98** [comment]
Successfully merged Congratulations!!

**Comment by s4shantanu** [comment]
Thank you kaivalya.

**Comment by s4shantanu** [comment]
Hey Kaivalya,
I have a question, If I contribute more in the same repo then my pull request can be count in hacktoberfest 2022?

**Comment by s4shantanu** [comment]
Hey, @kaivalya98 My submission was excluded which rules have you not followed?

**Pull request merged**
